#ifndef ARDUINO_SECRETS_H
#define ARDUINO_SECRETS_H

#define SECRET_BLYNK_TEMPLATE_ID "TMPL3Bi-TAfoP"
#define SECRET_BLYNK_TEMPLATE_NAME "Wheelchair"
#define SECRET_BLYNK_AUTH_TOKEN "4XUaURcdhNBz1RyO6XSmgdYS3aUBxpSd"
#define SECRET_WIFI_SSID "SGN JIO"
#define SECRET_WIFI_PASS "sgn%135135"

#endif
